### ISSUE TITLE
No feature for tracking current batsman and bowler stats

### ISSUE THREAD

**Issue by vohrakunal** [sarthology/criCLI#1]
There is no feature to track current batsman score..

**Comment by sharmarajat01** [comment]
i just used it, its good to see the current score but there should be a proper summary for the last 5 overs or anything !!

**Comment by sarthology** [comment]
How about we collaborate on this? 😃

**Comment by sharmarajat01** [comment]
> How about we collaborate on this?

I am ready to accept the challenge. you have me to work on this open project ! O_O
